version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: olvy
      POSTGRES_PASSWORD: olvysecurepassword
      POSTGRES_DB: olvydb
    ports:
      - "5432:5432"
    networks:
      - olvy-net

  backend:
    build: ./backend
    command: python -m backend.main
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://olvy:olvysecurepassword@db:5432/olvydb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CARTA_API_KEY: ${CARTA_API_KEY}
      CRM_API_KEY: ${CRM_API_KEY}
    networks:
      - olvy-net

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - olvy-net

networks:
  olvy-net:
    driver: bridge

volumes:
  postgres_data: